# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  sequence_diagrams: false
  changed_files_summary: true
  abort_on_close: true
  path_instructions:
    - path: "**/*"
      instructions: |
        1. When I push or force push, please review the open conversations. If the new changes resolve the open conversations, please comment on the conversation that this conversation has been resolved.
        2. Please note that issues that have already been considered should not be raised
        3. If there are new changes, please regenerate the PR title and PR description
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
chat:
  auto_reply: true
