name: momoino

services:
  database:
    image: postgres:16.0
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${SUPER_DB_USER}
      POSTGRES_PASSWORD: ${SUPER_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: keycloak-user.pwd
        target: /keycloak-user.pwd
      - source: momoino-user.pwd
        target: /momoino-user.pwd
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    restart: always
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - database
    command: start-dev --import-realm
    volumes:
      - ./.docker/keycloak:/opt/keycloak/data/import
    networks:
    - backend

networks:
  backend:

volumes:
  pgdata:

configs:
  keycloak-user.pwd:
    content: "${KEYCLOAK_DB_PASSWORD}"
  momoino-user.pwd:
    content: "${MOMOINO_DB_PASSWORD}"
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "${MOMOINO_DB_NAME}",
            "Host": "database",
            "Port": 5432,
            "MaintenanceDB": "${MOMOINO_DB_NAME}",
            "Username": "${MOMOINO_DB_USERNAME}",
            "PassFile": "/momoino-user.pwd",
            "SSLMode": "prefer"
          },
          "2": {
            "Group": "Servers",
            "Name": "${KEYCLOAK_DB_NAME}",
            "Host": "database",
            "Port": 5432,
            "MaintenanceDB": "${KEYCLOAK_DB_NAME}",
            "Username": "${KEYCLOAK_DB_USERNAME}",
            "PassFile": "/keycloak-user.pwd",
            "SSLMode": "prefer"
          }
        }
      }
