// Code generated by mockery v2.49.0. DO NOT EDIT.

package mockcore

import mock "github.com/stretchr/testify/mock"

// MockEncryptor is an autogenerated mock type for the Encryptor type
type MockEncryptor struct {
	mock.Mock
}

type MockEncryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptor) EXPECT() *MockEncryptor_Expecter {
	return &MockEncryptor_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: encryptedText
func (_m *MockEncryptor) Decrypt(encryptedText string) (*string, error) {
	ret := _m.Called(encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*string, error)); ok {
		return rf(encryptedText)
	}
	if rf, ok := ret.Get(0).(func(string) *string); ok {
		r0 = rf(encryptedText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encryptedText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncryptor_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEncryptor_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encryptedText string
func (_e *MockEncryptor_Expecter) Decrypt(encryptedText interface{}) *MockEncryptor_Decrypt_Call {
	return &MockEncryptor_Decrypt_Call{Call: _e.mock.On("Decrypt", encryptedText)}
}

func (_c *MockEncryptor_Decrypt_Call) Run(run func(encryptedText string)) *MockEncryptor_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEncryptor_Decrypt_Call) Return(_a0 *string, _a1 error) *MockEncryptor_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncryptor_Decrypt_Call) RunAndReturn(run func(string) (*string, error)) *MockEncryptor_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *MockEncryptor) Encrypt(plaintext []byte) (*string, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*string, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func([]byte) *string); ok {
		r0 = rf(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncryptor_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryptor_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext []byte
func (_e *MockEncryptor_Expecter) Encrypt(plaintext interface{}) *MockEncryptor_Encrypt_Call {
	return &MockEncryptor_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *MockEncryptor_Encrypt_Call) Run(run func(plaintext []byte)) *MockEncryptor_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) Return(_a0 *string, _a1 error) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncryptor_Encrypt_Call) RunAndReturn(run func([]byte) (*string, error)) *MockEncryptor_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncryptor creates a new instance of MockEncryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptor {
	mock := &MockEncryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
