// Code generated by mockery v2.46.2. DO NOT EDIT.

package mockcore

import (
	http "net/http"
	core "wano-island/common/core"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPRoute is an autogenerated mock type for the HTTPRoute type
type MockHTTPRoute struct {
	mock.Mock
}

type MockHTTPRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPRoute) EXPECT() *MockHTTPRoute_Expecter {
	return &MockHTTPRoute_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with given fields:
func (_m *MockHTTPRoute) Config() *core.HTTPRouteConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *core.HTTPRouteConfig
	if rf, ok := ret.Get(0).(func() *core.HTTPRouteConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.HTTPRouteConfig)
		}
	}

	return r0
}

// MockHTTPRoute_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockHTTPRoute_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockHTTPRoute_Expecter) Config() *MockHTTPRoute_Config_Call {
	return &MockHTTPRoute_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockHTTPRoute_Config_Call) Run(run func()) *MockHTTPRoute_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPRoute_Config_Call) Return(_a0 *core.HTTPRouteConfig) *MockHTTPRoute_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPRoute_Config_Call) RunAndReturn(run func() *core.HTTPRouteConfig) *MockHTTPRoute_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockHTTPRoute) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// MockHTTPRoute_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockHTTPRoute_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *MockHTTPRoute_Expecter) ServeHTTP(_a0 interface{}, _a1 interface{}) *MockHTTPRoute_ServeHTTP_Call {
	return &MockHTTPRoute_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", _a0, _a1)}
}

func (_c *MockHTTPRoute_ServeHTTP_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *MockHTTPRoute_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHTTPRoute_ServeHTTP_Call) Return() *MockHTTPRoute_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPRoute_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockHTTPRoute_ServeHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPRoute creates a new instance of MockHTTPRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPRoute {
	mock := &MockHTTPRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
