run:
  timeout: 5m
  tests: true

linters-settings:
  sloglint:
    no-mixed-args: true
    kv-only: false
    attr-only: true
    key-naming-case: "kebab"
    args-on-sep-lines: true
    no-global: "all"
    context: "scope"
    forbidden-keys:
      - time
      - level
      - source
      - msg
  nestif:
    min-complexity: 2
  gocognit:
    min-complexity: 20
  cyclop:
    max-complexity: 30
    package-average: 10
  errcheck:
    check-type-assertions: true
  exhaustive:
    check:
      - switch
      - map
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nakedret:
    max-func-lines: 0
  nolintlint:
    allow-no-explanation:
      - funlen
      - gocognit
      - lll
    require-specific: true
    require-explanation: true
  lll:
    tab-width: 1
    line-length: 120
  importas:
    no-unaliased: true
    alias:
      - pkg: wano-island/migration/core
        alias: migrationCore
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
              - github.com/onsi/ginkgo/v2
              - github.com/onsi/gomega
              - github.com/onsi/gomega/gstruct
              - github.com/onsi/gomega/gleak
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - fx.Option
      - sqlmock.Sqlmock
  ginkgolinter:
    forbid-focus-container: true
    force-expect-to: true
    validate-async-intervals: true
    forbid-spec-pollution: true
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: true
    disable-dec-num-check: true
    disable-type-dec-num-check: true
    disable-const-dec-num-check: true
    disable-var-dec-num-check: true
  gomoddirectives:
    replace-allow-list:
      # TODO: Please remove this when the official package allows any type of `contextKey`.
      - github.com/orandin/slog-gorm
  stylecheck:
    checks:
      - all
      - -ST1001

linters:
  disable-all: true

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    # - exportloopref
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    - intrange
    - lll
    # - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

    - ginkgolinter
    - godox
    - prealloc

    - importas
    # - err113

    - wsl
    - ireturn
    - ginkgolinter
    - decorder

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
