import { AuthProvider } from '@/internal/modules/auth/AuthProvider';
import { QueryClientProvider } from '@/internal/modules/core/react-query/provider';
import { AppProvider } from '@/internal/modules/core/ui';
import { theme } from '@/internal/modules/core/ui/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { PropsWithChildren } from 'react';

export const fetchCache = 'default-cache';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html suppressHydrationWarning lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <InitColorSchemeScript attribute="class" />
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <QueryClientProvider>
                <AppProvider
                  value={{
                    authProvider: AuthProvider,
                  }}
                >
                  {children}
                </AppProvider>
              </QueryClientProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
