openapi: 3.0.3

info:
  title: wano-island/wano
  version: 1.0.0

components:
  schemas:
    Response:
      type: object
      properties:
        message:
          type: string
        messageId:
          type: string
        timestamp:
          type: string
          format: date-time
